language: go

branches:
  only:
  - master
  - /^v.*$/
  - /^issue-\d+/

go:
  - "1.13.x"

sudo: false

services:
  - docker

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1
  - make dep

script:
  # Code coverage and testing
  - make lint
  - make coverage
  - bash <(curl -s https://codecov.io/bash)
  # Docker build and deployment
  # Push only if:
  # - triggered by a push to master
  # - triggered by a push to a tag
  # - not triggered by a pull request
  # https://docs.travis-ci.com/user/environment-variables/
  - |
    export VERSION=${TRAVIS_TAG:-"latest"}
    make docker VERSION=${VERSION}
    echo ${DOCKER_PASSWORD} | docker login --password-stdin -u ${DOCKER_USER}
    if [[ (! -z ${TRAVIS_TAG} || ${TRAVIS_BRANCH} == "master") && ${TRAVIS_PULL_REQUEST} == false ]]; then
      make docker-push VERSION=${VERSION}
    elif [[ ${TRAVIS_PULL_REQUEST} == "true" ]]; then
      make docker-push VERSION=${TRAVIS_PULL_REQUEST_BRANCH}
    fi
    
    make darwin VERSION=${VERSION}

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - ./bin/prometheus-msteams-darwin-amd64
    - ./bin/prometheus-msteams-linux-amd64
    - ./bin/shasum256.txt
    - ./default-message-card.tmpl
  skip_cleanup: true
  on:
    tags: true

