language: go

branches:
  only:
  - master
  - /^v.*$/
  - /^issue-\d+/

go:
  - "1.13.x"

sudo: false

services:
  - docker

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1
  - make dep

script:
  # Code coverage and testing
  - make lint
  - make coverage
  - bash <(curl -s https://codecov.io/bash)
  # Docker build and deployment
  # Push only if:
  # - triggered by a push to master
  # - triggered by a push to a tag
  # - not triggered by a pull request
  # https://docs.travis-ci.com/user/environment-variables/
  - |
    export VERSION=${TRAVIS_TAG:-${TRAVIS_BRANCH}}
    echo "Building app version $VERSION"

    make all VERSION=${VERSION}
    make docker VERSION=${VERSION}

    echo ${DOCKER_PASSWORD} | docker login --password-stdin -u ${DOCKER_USER}

    if [[ -n ${TRAVIS_TAG} || ${TRAVIS_BRANCH} == "master" ]]; then
      docker-tag-latest VERSION=${VERSION}
      make docker-push VERSION=latest
      make docker-push VERSION=${VERSION}
    fi

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - ./bin/prometheus-msteams-darwin-amd64
    - ./bin/prometheus-msteams-linux-amd64
    - ./bin/shasum256.txt
    - ./default-message-card.tmpl
  skip_cleanup: true
  on:
    tags: true

