---
replicaCount: 1

image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: v1.4.1
  pullPolicy: Always

# imageCredentials is a map of registry, username and password
#   which will be used to pull the image from a private repository
#   specified with image.repository
# imageCredentials:
#   repository: myprivaterepository:5000
#   username: the_username
#   password: the_password

extraEnvs:

container:
  port: 2000
  additionalArgs: []

resources:
  limits:
    cpu: 10m
    memory: 32Mi
  requests:
    cpu: 1m
    memory: 8Mi

service:
  type: ClusterIP
  port: 2000

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

priorityClassName: ""

metrics:
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    scrapeInterval: 30s

connectors: []
connectors_with_custom_templates: []

## Specify the custom message card template for MS teams
# customCardTemplate: |
#   {{ define "teams.card" }}
#   {...}
#   {{ end }}
