---
replicaCount: 1

image:
  repository: bzon/prometheus-msteams
  tag: v1.1.0
  pullPolicy: Always

extraEnvs:
  - name: idle-conn-timeout
    value: 90
  - name: max-idle-conns
    value: 100
  - name: tls-handshake-timeout
    value: 30

container:
  port: 2000
  additionalArgs: []

resources:
  limits:
    cpu: 10m
    memory: 32Mi
  requests:
    cpu: 1m
    memory: 8Mi

service:
  type: ClusterIP
  port: 2000

nodeSelector: {}

tolerations: []

affinity: {}

# Replace this!
connectors:
  - alertmanager: https://outlook.office.com/webhook/xxxxx/IncomingWebhook/xxxx/xxxxx
