---
replicaCount: 1

image:
  repository: bzon/prometheus-msteams
  tag: v1.1.4
  pullPolicy: Always

extraEnvs:

container:
  port: 2000
  additionalArgs: []

resources:
  limits:
    cpu: 10m
    memory: 32Mi
  requests:
    cpu: 1m
    memory: 8Mi

service:
  type: ClusterIP
  port: 2000

nodeSelector: {}

tolerations: []

affinity: {}

# Replace this!
connectors:
  - alertmanager: https://outlook.office.com/webhook/xxxxx/IncomingWebhook/xxxx/xxxxx

# Provide your own ConfigMap with a template by creating it separately, and
# provide the configmap's name here. The ConfigMap should have one key - "card.tmpl"
# with a card definition as outlined here:
# https://github.com/bzon/prometheus-msteams/blob/master/README.md#customise-messages-to-ms-teams
templateConfigMap: ""