---
replicaCount: 1

image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: v1.4.1
  pullPolicy: Always

imagePullSecrets: []

extraEnvs:

container:
  port: 2000
  additionalArgs: []

resources:
  limits:
    cpu: 10m
    memory: 32Mi
  requests:
    cpu: 1m
    memory: 8Mi

service:
  type: ClusterIP
  port: 2000

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

priorityClassName: ""

metrics:
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    scrapeInterval: 30s

connectors: []

# Templates defined here can be used in connectorsWithCustomTemplates and are mounted into /etc/template/
customCardTemplates: []
# - templateFileName: custom-message-card.tmpl
#   content: |
#     {{ define "teams.card" }}
#     {...}
#     {{ end }}

# ref: https://github.com/prometheus-msteams/prometheus-msteams#customise-messages-per-ms-teams-channel
# Templates are mounted into /etc/template/
connectorsWithCustomTemplates: []
# - request_path: /alert2
#   template_file: /etc/template/custom-message-card.tmpl
#   webhook_url: <webhook>
#   escape_underscores: true

## Specify the custom message card template for MS teams
# customCardTemplate: |
#   {{ define "teams.card" }}
#   {...}
#   {{ end }}
