---
apiVersion: v1
kind: ConfigMap
metadata:
 name: prometheus-msteams-card-template
binaryData:
  card.tmpl: |-
{{- if .Values.customCardTemplate }}
{{ .Values.customCardTemplate | b64enc | indent 4 }}
{{- else }}
{{ .Files.Get "card.tmpl" | b64enc | indent 4 }}
{{- end }}