---
apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ template "app.name" . }}-card-template
binaryData:
  card.tmpl: |-
{{ .Files.Get "card.tmpl" | b64enc | indent 4 }}
{{- range $index, $customCardTemplate := .Values.connectorsWithCustomTemplates }}
{{- if hasKey $customCardTemplate "template_file" }}
  custom_card_{{ $index }}.tmpl: |-
{{ $customCardTemplate.template_file | b64enc | indent 4 }}
{{- end }}
{{- end }}
